- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Free Trial(9b2382f0-ab49-403b-b7d6-929dc50712eb)'
        appType: 'webAppLinux'
        appName: 'hello-k4wld-spring'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
        runtimeStack: 'JAVA|8-jre8'